# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None

# 获取当前目录
current_dir = os.path.dirname(os.path.abspath(SPEC))
base_dir = os.path.dirname(current_dir)

a = Analysis(
    ['run.py'],
    pathex=[base_dir],
    binaries=[],
    datas=[
        ('app', 'app'),
        ('routers', 'routers'),
        ('crud', 'crud'),
        ('models', 'models'),
        ('schemas', 'schemas'),
        ('utils', 'utils'),
    ],
    hiddenimports=[
        # FastAPI 核心
        'uvicorn',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'fastapi.applications',
        'fastapi.routing',
        'fastapi.middleware',
        'starlette',
        'starlette.middleware',
        'starlette.routing',
        
        # 数据验证和序列化
        'pydantic',
        'pydantic.main',
        'pydantic.fields',
        'pydantic.validators',
        'typing_extensions',
        
        # 数据库
        'sqlalchemy',
        'sqlalchemy.orm',
        'sqlalchemy.engine',
        'sqlalchemy.pool',
        'sqlalchemy.ext',
        'sqlalchemy.ext.declarative',
        'pymysql',
        'pymysql.connections',
        'pymysql.cursors',
        
        # 文件和模板
        'jinja2',
        'jinja2.Environment',
        'markdown',
        
        # 后端模块
        'app.database',
        'app.cache',
        'routers.product',
        'routers.customer',
        'routers.supplier',
        'routers.pi',
        'routers.purchase',
        'routers.shipment',
        'routers.inventory',
        'routers.payment',
        'routers.quote',
        'routers.product_category',
        'routers.image',
        'routers.auth',
        'routers.product_supplier',
        'crud.product',
        'crud.customer',
        'crud.supplier',
        'crud.pi',
        'crud.purchase',
        'crud.shipment',
        'crud.inventory',
        'crud.payment',
        'crud.quote',
        'crud.supplier',
        'crud.product_supplier',
        'models.product',
        'models.customer',
        'models.supplier',
        'models.pi',
        'models.purchase',
        'models.shipment',
        'models.inventory',
        'models.payment',
        'models.quote',
        'models.user',
        'models.product_category',
        'models.product_supplier',
        'schemas.product',
        'schemas.customer',
        'schemas.supplier',
        'schemas.pi',
        'schemas.purchase',
        'schemas.shipment',
        'schemas.inventory',
        'schemas.payment',
        'schemas.quote',
        'schemas.product_category',
        'schemas.product_supplier',
        'utils.number_generator',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'tkinter',
        'test',
        'unittest',
        'PyQt5',
        'PyQt6',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PI_Manager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)